server:
  port: 7072

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/Java9TahminDB
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  # Kullanım kolaylığı için şifreler açıkca verilmiştir.
  #  secretKey: ${java9secretkey}
  #  issuer: ${java9issuer}
  #  audience: ${java9audience}
  secretKey: java9Marathon4
  issuer: dorukjava9
  audience: java9